# Generated by Django 4.1 on 2023-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dni',
            field=models.IntegerField(default=123441234),
            preserve_default=False,
        ),
    ]
