# Generated by Django 4.1 on 2023-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0002_patient_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
