# Generated by Django 4.1 on 2023-01-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0004_alter_medicines_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consultorio.patient'),
        ),
    ]
