# Generated by Django 4.1 on 2023-01-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0006_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='Consultorio.patient'),
        ),
    ]
