# Generated by Django 4.1 on 2023-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0008_alter_orders_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('Laboratorio', 'Laboratorio'), ('Consulta con profesional', 'Consulta con profesional'), ('Estudios', 'Estudios'), ('Otros', 'Otros')], max_length=100),
        ),
    ]
