# Generated by Django 4.1 on 2023-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0009_alter_orders_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='home_images')),
                ('day_sentence', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
