# Generated by Django 4.1 on 2023-02-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0011_alter_media_options_rename_img_media_media_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Consultorio.patient'),
        ),
    ]
